# Generated by Django 5.1.5 on 2025-01-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="My_Profile_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("learning_topic", models.CharField(max_length=50)),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("Elementary", "Elementary School"),
                            ("Middle", "Middle School"),
                            ("High", "High School"),
                            ("Undergraduate", "Undergraduate"),
                            ("Graduate", "Graduate"),
                            ("PhD", "Doctorate"),
                        ],
                        default="Elementary",
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
